install:
	mkdir -p "$${HOME}/.claude/skills"
	ln -f -s "$(shell pwd)/CLAUDE.md" "$${HOME}/.claude/CLAUDE.md"
	ln -f -s "$(shell pwd)/skills/java-style" "$${HOME}/.claude/skills/java-style"
	ln -f -s "$(shell pwd)/skills/sql-style" "$${HOME}/.claude/skills/sql-style"
.PHONY: install
