source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle command-not-found
antigen bundle git
#antigen bundle ssh-agent
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme win0err/aphrodite-terminal-theme 
antigen apply

export EDITOR=vim

export DEVELOPMENT_HOME="$HOME/development"

export GOROOT="$HOME/.local/go"
export GOPATH="$DEVELOPMENT_HOME/go"
export GO111MODULE=on

export CARGO_HOME="$HOME/.cargo"

export BUILDAH_FORMAT='docker'

export DOTNET_USE_POLLING_FILE_WATCHER=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1

export PATH="$HOME/.local/bin:$GOROOT/bin:$GOPATH/bin:$CARGO_HOME/bin:$PATH"

if [ -d "$HOME/.dotnet/tools" ]; then
    export PATH="$HOME/.dotnet/tools:$PATH"
fi

if [ -d "$HOME/.poetry" ]; then
    export PATH="$HOME/.poetry/bin:$PATH"
fi

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

if [ -f "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
