source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle command-not-found
antigen bundle git
antigen bundle gpg-agent
antigen bundle ssh-agent

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme win0err/aphrodite-terminal-theme 

antigen apply

# Load additional host-specific scripts
if [ -d "$HOME/.zshrc.d" ]; then
    for file in $HOME/.zshrc.d/*.zsh; do
        source "$file"
    done
fi

# Enable fzf if available
if [ -f ~/.fzf.zsh ]; then
    # Installed via install script
    source ~/.fzf.zsh
elif [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
    # Installed via APT
    source /usr/share/doc/fzf/examples/completion.zsh
fi

# Enable metasploit & msfvenom completions if available
if [ -d "$INFOSEC_HOME/tools/metasploit-framework/external/zsh" ]; then
    fpath=("$INFOSEC_HOME/tools/metasploit-framework/external/zsh" $fpath)
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
